// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Link struct {
	ID         string       `json:"id"`
	Url        string       `json:"url"`
	CreatedAt  time.Time    `json:"created_at"`
	ConsumedAt sql.NullTime `json:"consumed_at"`
}

type LinkPolicy struct {
	ID        int64           `json:"id"`
	LinkID    string          `json:"link_id"`
	Kind      string          `json:"kind"`
	Config    json.RawMessage `json:"config"`
	CreatedAt time.Time       `json:"created_at"`
}

type LinkVisit struct {
	ID        int64       `json:"id"`
	LinkID    string      `json:"link_id"`
	VisitedAt time.Time   `json:"visited_at"`
	IpAddress pqtype.Inet `json:"ip_address"`
}
