// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const checkShortCodeExists = `-- name: CheckShortCodeExists :one
SELECT EXISTS(SELECT 1 FROM links WHERE id = $1)
`

func (q *Queries) CheckShortCodeExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkShortCodeExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const consumeSingleUseLink = `-- name: ConsumeSingleUseLink :exec
UPDATE links
SET consumed_at = NOW()
WHERE id = $1 AND consumed_at IS NULL
RETURNING 1
`

func (q *Queries) ConsumeSingleUseLink(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, consumeSingleUseLink, id)
	return err
}

const createLink = `-- name: CreateLink :exec
INSERT INTO links (id, url, created_at)
VALUES ($1, $2, $3)
`

type CreateLinkParams struct {
	ID        string    `json:"id"`
	Url       string    `json:"url"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) error {
	_, err := q.db.ExecContext(ctx, createLink, arg.ID, arg.Url, arg.CreatedAt)
	return err
}

const createLinkPolicy = `-- name: CreateLinkPolicy :exec
INSERT INTO link_policies (link_id, kind, config)
VALUES ($1, $2, $3)
`

type CreateLinkPolicyParams struct {
	LinkID string          `json:"link_id"`
	Kind   string          `json:"kind"`
	Config json.RawMessage `json:"config"`
}

func (q *Queries) CreateLinkPolicy(ctx context.Context, arg CreateLinkPolicyParams) error {
	_, err := q.db.ExecContext(ctx, createLinkPolicy, arg.LinkID, arg.Kind, arg.Config)
	return err
}

const getLink = `-- name: GetLink :one
SELECT
    l.id,
    l.url,
    l.created_at,
    l.consumed_at,
    JSON_AGG(
        JSON_BUILD_OBJECT(
            'kind', lp.kind, 
            'config', lp.config
        )
    ) AS policies
FROM links l
INNER JOIN link_policies lp ON l.id = lp.link_id
WHERE l.id = $1
GROUP BY 
    l.id, 
    l.url, 
    l.created_at, 
    l.consumed_at
`

type GetLinkRow struct {
	ID         string          `json:"id"`
	Url        string          `json:"url"`
	CreatedAt  time.Time       `json:"created_at"`
	ConsumedAt sql.NullTime    `json:"consumed_at"`
	Policies   json.RawMessage `json:"policies"`
}

func (q *Queries) GetLink(ctx context.Context, id string) (GetLinkRow, error) {
	row := q.db.QueryRowContext(ctx, getLink, id)
	var i GetLinkRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.CreatedAt,
		&i.ConsumedAt,
		&i.Policies,
	)
	return i, err
}

const logLinkVisit = `-- name: LogLinkVisit :exec
INSERT INTO link_visits(link_id, visited_at, ip_address)
VALUES($1, $2, $3)
`

type LogLinkVisitParams struct {
	LinkID    string      `json:"link_id"`
	VisitedAt time.Time   `json:"visited_at"`
	IpAddress pqtype.Inet `json:"ip_address"`
}

func (q *Queries) LogLinkVisit(ctx context.Context, arg LogLinkVisitParams) error {
	_, err := q.db.ExecContext(ctx, logLinkVisit, arg.LinkID, arg.VisitedAt, arg.IpAddress)
	return err
}
